discord:
  notifications:
    server-start: true
    server-stop: true
    
    connection-messages: true
    player-death-messages: true
  
  colors:
    # color values were taken from https://htmlcolorcodes.com/minecraft-color-codes/
    black: 65793 # Color with value 0 is means no color, so we use a very dark gray instead
    dark_blue: 170
    dark_green: 43520
    dark_aqua: 43690
    dark_red: 11141120
    dark_purple: 11141290
    gold: 16755200
    gray: 11184810
    dark_gray: 5592405
    blue: 5592575
    green: 5635925
    aqua: 5636095
    red: 16733525
    light_purple: 16733695
    yellow: 16777045
    white: 16777215

messages:
  plugin-enabled: '%name% v%version% has been enabled!'
  
  chat:
    minecraft-format: '&e<%username%> &f%message%&7%attachments%'
    minecraft-edited-format: '&e<%username%> &f%message%&7%attachments% &8&l(Edited)'
    attachment-spoiler: ' (spoiler)'
    attachment-separator: ', '
    discord-format: '**<%player%>:** %message%'
  
  player:
    connected: "**%player%** has connected to the server. ğŸ˜ ğŸ‰"
    disconnected: "**%player%** has disconnected from the server. ğŸ˜­"
    death: "[%death_message%] ğŸ’€"

  custom-death-messages:
    lava: "**%player%** fell into lava. ğŸ”¥ğŸ¥µ"
    fire: "**%player%** burned to death. ğŸ”¥ğŸ¥µ"
    fall: "**%player%** fell from a high place. ğŸª‚"
    void: "**%player%** fell into the void. âœ¨"
    drowing: "**%player%** drowned. ğŸŒŠ"

  server:
    start: |-
      ğŸŸ¢ **Minecraft Server is now ONLINE!** ğŸŸ¢

      âš”ï¸ The server is up and running. Time to gather your friends, build amazing structures, and embark on new adventures. â›ï¸
      Happy crafting!

      **Server Address:** `my.minecraft.server.com`

      @everyone
    stop: |-
      ğŸ”´ **Minecraft Server is now OFFLINE!** ğŸ”´

      âš”ï¸ The server has shut down. It's time to rest, plan new builds, and prepare for upcoming adventures. â›ï¸
      Thanks for playing!

      **Server Address:** `my.minecraft.server.com`

      @everyone

