messages:
  plugin-enabled: '%name% v%version% has been enabled!'
  
  chat:
    minecraft-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments%'
    minecraft-edited-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments%
      &8&l(Edited)'
    attachment-spoiler: ' (spoiler)'
    attachment-separator: ', '
    discord-format: '**<%player%>:** %message%'
  
  player:
    joined: '**%player%** se ha metido a la droga ğŸ˜ ğŸ‰'
    left: '**%player%** se ha ido ğŸ˜­'
    death: 'Jajajaja se murÃ­o el subnormal de %player% porque `%death_message%`'
    murder: 'El cabronazo de **%killer%** ha matado a **%victim%** ğŸ˜ˆ'
  
  custom-death-messages:
    lava: '**%player%** se ha caÃ­do en lava. ğŸ”¥ğŸ¥µ'
    fire: '**%player%** se ha quemado. ğŸ”¥ğŸ¥µ'
    fall: '**%player%** se ha caÃ­do de una gran altura. ğŸª‚âœ¨'
    void: '**%player%** se ha caÃ­do al vacÃ­o. ğŸŒŒğŸª‚'
    drowing: '**%player%** se ha ahogado. ğŸŒŠ'
  
  server:
    start: "ğŸŸ¢ **PÃ­oCraft se ha ABIERTO!** ğŸŸ¢\n\nâš”ï¸ El server se acaba de encender.\
      \ Es hora de llamar a tus amigos, conectarse, hacer construcciones Ã©picas, y\
      \ embarcarse en nuevas aventuras. â›ï¸ \nHappy Crafting! <:pio:1246938937230889041>\
      \ \n\n**IP del Servidor:** `mc.electrodiux.com`\n\n<@&1246836960954417173>"
    stop: |-
      ğŸ”´ **PÃ­oCraft se ha CERRADO!** ğŸ”´

      âš”ï¸ El server se acaba de apagar. Es momento de descansar, planificar nuevas construcciones, y prepararse para las prÃ³ximas aventuras. â›ï¸
      Gracias por jugar! <:pio:1246938937230889041>

      **IP del Servidor:** `mc.electrodiux.com`

      <@&1246836960954417173>
