messages:
  plugin-enabled: '%name% v%version% has been enabled!'

  chat:
    minecraft-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments%'
    minecraft-edited-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments% &8&l(Edited)'
    attachment-spoiler: ' (spoiler)'
    attachment-separator: ', '
    discord-format: '**<%player%>:** %message%'

  player:
    joined: '**%player%** has joined the game ğŸ˜ ğŸ‰'
    left: '**%player%** has left the game ğŸ˜­'
    death: 'Haha, %player% died because `%death_message%`'
    murder: '**%killer%** has killed **%victim%** ğŸ˜ˆ'

  custom-death-messages:
    lava: '**%player%** fell into lava. ğŸ”¥ğŸ¥µ'
    fire: '**%player%** burned to death. ğŸ”¥ğŸ¥µ'
    fall: '**%player%** fell from a high place. ğŸª‚âœ¨'
    void: '**%player%** fell into the void. ğŸŒŒğŸª‚'
    drowning: '**%player%** drowned. ğŸŒŠ'

  server:
    start: |-
      ğŸŸ¢ **The server has STARTED!** ğŸŸ¢

      âš”ï¸ The server is now online. Gather your friends, start building epic structures, and embark on new adventures. â›ï¸
      Happy Crafting!

      **Server IP:** `mc.yourserver.com`

      <@&your-role-id>
    stop: |-
      ğŸ”´ **The server has SHUT DOWN!** ğŸ”´

      âš”ï¸ The server is now offline. Time to rest, plan new builds, and prepare for future adventures. â›ï¸
      Thank you for playing!

      **Server IP:** `mc.yourserver.com`

      <@&your-role-id>
