messages:
  chat:
    minecraft-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments%'
    minecraft-edited-format: '[%guild% -> %channel%] &e<%username%> &f%message%&7%attachments% &8&l(Edited)'
    attachment-spoiler: ' (spoiler)'
    attachment-separator: ', '
    discord-format: '**<%player%>:** %message%'

  player:
    joined: '**%player_name%** has joined the game ğŸ˜ ğŸ‰'
    left: '**%player_name%** has left the game ğŸ˜­'
    death: 'Haha, %player_name% died because `%death_message%`'
    murder: '**%killer_name%** has killed **%victim_name%** ğŸ˜ˆ'

  custom-death-messages:
    lava: '%death_message% ğŸ”¥ğŸ¥µ'
    fire: '%death_message% ğŸ”¥ğŸ¥µ'
    fall: '%death_message% ğŸª‚âœ¨'
    void: '%death_message% ğŸŒŒğŸª‚'
    drowning: '%death_message% ğŸŒŠ'

  server:
    start: |-
      ğŸŸ¢ **The server has STARTED!** ğŸŸ¢

      âš”ï¸ The server is now online. Gather your friends, start building epic structures, and embark on new adventures. â›ï¸
      Happy Crafting!

      **Server IP:** `mc.yourserver.com`

      <@&your-role-id>
    stop: |-
      ğŸ”´ **The server has SHUT DOWN!** ğŸ”´

      âš”ï¸ The server is now offline. Time to rest, plan new builds, and prepare for future adventures. â›ï¸
      Thank you for playing!

      **Server IP:** `mc.yourserver.com`

      <@&your-role-id>
